M48
; DRILL file {KiCad 9.0.5} date 2025-12-11T22:34:33+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-11T22:34:33+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X57.152Y-38.556
X57.218Y-87.246
X95.977Y-38.523
X96.129Y-87.255
M30
